inputs:
  release_tag:
    description: 'Release tag to build'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure Git Commiter
      uses: ./.github/actions/configure_git_commiter
    - name: Apply docker version
      shell: bash
      run: |
        ${{ github.action_path }}/apply-docker-version.sh ${{ inputs.release_tag }}
