inputs:
  from_branch:
    description: 'Branch to merge from'
    required: true
  to_branch:
    description: 'Branch to merge into'
    required: true

runs:
  using: "composite"
  steps:
    - name: Do verified merge
      shell: bash
      run: |
        ${{ github.action_path }}/merge-branches-verified.sh --from ${{ inputs.from_branch }} --to ${{ inputs.to_branch }}