# This worjflow is a part of release automation process.
# It is intended to be run with workflow_dispatch event by the automation.

# Warning: Workflow does switch branches and this may lead to confusion when changing workflow actions.
# The usual safety rule is to make changes to workflow or actions in base branch (e.g, release/8.X)
# Version branches (e.g, 8.0.10-rc5-int8) will merge changes from base branch automatically.
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to build'
        required: true

jobs:
  prepare-release:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Redis Release Archive
        uses: ./.github/actions/validate-redis-release-archive
        with:
          release_tag: ${{ github.event.inputs.release_tag }}

      - name: Ensure Release Branch
        id: ensure-branch
        uses: ./.github/actions/ensure-release-branch
        with:
          release_tag: ${{ github.event.inputs.release_tag }}
          allow_modify: true

      - name: Apply Docker Version
        uses: ./.github/actions/apply-docker-version
        with:
          release_tag: ${{ github.event.inputs.release_tag }}
          release_version_branch: ${{ steps.ensure-branch.outputs.release_version_branch }}

  build-and-test:
    needs: prepare-release
    if: false
    uses: ./.github/workflows/pre-merge.yml
    secrets: inherit
    with:
      release_tag: ${{ inputs.release_tag }}

