on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to build'
        required: true

jobs:
  build-and-test:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate Redis Release Archive
        uses: ./.github/actions/validate-redis-release-archive
        with:
          release_tag: ${{ github.event.inputs.release_tag }}

      - name: Ensure Release Branch
        uses: ./.github/actions/ensure-release-branch
        with:
          release_tag: ${{ github.event.inputs.release_tag }}